seed: 42
data:
  csv_path: data/heart.csv
  target: target
  split:
    test_size: 0.3
    stratify: true
    random_state: 42
features:
  pca: true
  pca_components: 0.95
train:
  baseline: true
  dnn:
    epochs: 30
    batch_size: 64
    lr: 0.001
    hidden_sizes: [64, 32]
    dropout: 0.2

# IoT Simulation Parameters
sim:
  packet_bits: 512
  field_size_m: [500, 500]
  init_energy_J: 0.5
  base_station_xy: [250, 250]
  nodes_list: [50, 100, 150, 200, 250]
  rounds: 5  # Reduced for faster execution
  radio:
    e_elec: 5.0e-8
    eps_amp: 1.0e-10
    n: 2
  k_ch_ratio: 0.1
  aco:
    ants: 10  # Reduced for speed
    alpha: 1.0
    beta: 2.0
    rho_init: 0.5
    max_iter: 15  # Reduced for speed
    adaptive_evap: true
  ga:
    pop_size: 15  # Reduced for speed
    generations: 15  # Reduced for speed
    tournament_k: 3
    crossover_p: 0.9
    mutation_p: 0.02
  pareto:
    weights: {energy: 0.5, distance: 0.3, residual: 0.2}

# SA-DNN Parameters
sadnn:
  lr: 0.0001
  batch_size: 20
  hidden_sizes: [64, 32]
  gaussian_alpha: 0.5
  dropout: 0.2
  epochs: 30
  iwoa:
    enabled: true
    pop_size: 20
    generations: 50
    a_decay: 0.98
    spiral_prob: 0.5
    clamp: 1.0
    patience: 7
