seed: 42
sim:
  aco:
    adaptive_evap: true
    alpha: 1.0
    ants: 3
    beta: 2.0
    max_iter: 3
    rho_init: 0.5
  base_station_xy:
  - 250
  - 250
  field_size_m:
  - 500
  - 500
  ga:
    crossover_p: 0.9
    generations: 3
    mutation_p: 0.02
    pop_size: 3
    tournament_k: 2
  init_energy_J: 0.5
  k_ch_ratio: 0.1
  nodes_list:
  - 50
  packet_bits: 512
  pareto:
    weights:
      distance: 0.3
      energy: 0.5
      residual: 0.2
  radio:
    e_elec: 5.0e-08
    eps_amp: 1.0e-10
    n: 2
  rounds: 2
